package com.simcode.legacyadventures.game.actions

import com.simcode.legacyadventures.game.events.ContextChangeEvent

interface ContextActionResult

object ContextShouldStay: ContextActionResult
object ContextCanBeClosed: ContextActionResult
data class NewContextShouldBeStarted(val contextChangeEvent: ContextChangeEvent): ContextActionResult
object UnsupportedAction: ContextActionResult