version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u181
    steps:
      - checkout
      - run:
          name: Test
          command: ./gradlew clean test
      - run:
          name: Build
          command: ./gradlew build -x test
